appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oxVNW2K6QCFQ6T22HzcO7n0wjv7gTWnHM9MgYLLMa9YGH1QSGJdpeKuLb8RbgRft+A4SdPjaCHtfM3Quvwp1EaAwqV/3eUyB7HREExMe6TpMxjSoSqrn6yU5bpLQVpTZCZLLZn1YvmE3X8/a0qaMtBd2OFd9C8hQpN89mIES0N0ePluH377zYOybFflFBLMI/cEERvFJUyMWwtdDJNVU6ZuAFYlHLleAldCtVCOCQKrhz966CSqafirYdhDx7rptNi+fzxd8F5zz7expPJL1ns/JtMFRU3wAnF20lwfGfvSvyp88gE00NNFZ5ccH69bmcpB+P1p8vaHYd6OUkWHghK1Or6janXKTHKZaVE7imtD4Y4sZ7jJa3MXL0O4EvtfO9AmHEPAmSfzz02SdMNsxFKOX7QdiVGS9umC3UPqiIZaKCLuXdIpepcS1il1oY7cdPi/HcGzhHSwDOEbfov8HoD93Iam7JoCOnMYZXAnnWobb3/VVBAuuPrsA+fgYSsbbyH7Y89eFAY0+ZYT8KumM0EetGKf8hX6F8W9FqtpzZ8LrDYiBulJahEAwuLiLfoKjBPB4Fx5GezYCDMMFPeZZxtIwGgqzPCGWlBynoFAvmxH8nEvc8Skt33d2gPXtIUEJY3tZlPM1X/zHEn7rDA1ySNCzwIvbIhArdLZpnoROER8=}
